# Dependabot configuration
version: 2
updates:

  # Update dependencies via npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "15:00"
      timezone: "America/Cancun"
    labels:
      - "triage"
      - "deps"
    commit-message:
      prefix: "build"
      include: "scope"
    rebase-strategy: "auto"
    ignore:
      # ignore all updates of minor and patch
      - dependency-name: "*"
        update-types: ["version-update:semver-minor"]


  # Maintain dependencies for GitHub actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "triage"
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope"
