name: CI/CD

on:
  push:
    branches: [ master, next ]
  pull_request:
    branches: [ master, next ]

jobs:
  lint:
    name: Code Quality
    runs-on: ubuntu-latest
    env:
      node-version: 16.x
    steps:
      - name: git checkout HEAD
        uses: actions/checkout@v2

      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --prefer-offline --no-fund --no-audit

      - name: Lint
        run: npm run lint


  lint-commits:
    name: Semantic commits
    runs-on: ubuntu-latest
    env:
      node-version: 16.x
    steps:
      - name: git checkout HEAD
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --prefer-offline --no-fund --no-audit

      - name: PR commits check
        if: ${{ github.event_name == 'pull_request' }}
        run: npx commitlint --verbose
             --from ${{ github.event.pull_request.base.sha }}
             --to ${{ github.event.pull_request.head.sha }}


  build:
    name: Build
    runs-on: ubuntu-latest
    env:
        node-version: 16.x
    steps:
      - name: git checkout HEAD
        uses: actions/checkout@v2

      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --prefer-offline --no-fund --no-audit

      - name: Run build
        run: npm run build --if-present

      - name: Run unit-tests
        run: npm run test:unit

      - name: Upload bundle
        uses: actions/upload-artifact@v2.2.4
        with:
          name: dist-bundle
          path: dist/*
          if-no-files-found: error
          retention-days: 1


  integration:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
    steps:
      - name: git checkout HEAD
        uses: actions/checkout@v2

      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node-version }}
          cache: 'npm'

      - name: Download bundle
        uses: actions/download-artifact@v2
        with:
          name: dist-bundle
          path: dist/

      - name: Install dependencies
        run: npm ci --prefer-offline --no-fund --no-audit

      - name: Run plugin tests
        run: npm run test:plugin


  release:
    needs: 
      - lint
      - lint-commits
      - integration
    runs-on: ubuntu-latest
    steps:
      - name: git checkout HEAD
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'

      - name: Download bundle
        uses: actions/download-artifact@v2
        with:
          name: dist-bundle
          path: dist/

      - name: Install dependencies
        run: npm ci --prefer-offline --no-fund --no-audit

      - name: Run semantic-release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
