name: CI/CD

on:
  push:
    branches: [ master, next ]
  pull_request:
    branches: [ master, next ]

jobs:
  lint:
    name: Code Quality
    runs-on: ubuntu-latest
    env:
      node-version: 16.x
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node-version }}
          cache: 'npm'
      - run: npm ci --prefer-offline
      - run: npm run lint


  build:
    name: Build Code Bundle
    runs-on: ubuntu-latest
    env:
        node-version: 16.x
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node-version }}
          cache: 'npm'

      - run: npm ci --prefer-offline
      - run: npm run build --if-present
      - run: npm run test:unit

      - name: Upload bundle
        uses: actions/upload-artifact@v2.2.4
        with:
          name: dist-bundle
          path: dist/*
          if-no-files-found: error
          retention-days: 1


  integration:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ env.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node-version }}
          cache: 'npm'
      - name: Download bundle
        uses: actions/download-artifact@v2
        with:
          name: dist-bundle
          path: dist/
      - run: npm ci --prefer-offline      
      - run: npm run test:plugin


  release:
    needs: 
      - lint
      - integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'npm'
      - name: Download bundle
        uses: actions/download-artifact@v2
        with:
          name: dist-bundle
          path: dist/
      - run: npm ci --prefer-offline
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
